repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
        - id: isort
    - repo: https://github.com/python/black
      rev: 22.10.0
      hooks:
        - id: black
    - repo: https://gitlab.com/pycqa/flake8
      rev: 5.0.4
      hooks:
        - id: flake8
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-byte-order-marker
        - id: trailing-whitespace
        - id: end-of-file-fixer
