version: "3.9"

services:
  api:
    image: ghcr.io/ka7eh/ctsm-api:${VERSION:-latest}
    restart: unless-stopped
    entrypoint: /ctsm-api/docker/entrypoint_api.sh
    env_file:
      - .env
    environment:
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
      - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER:-admin}:${RABBITMQ_DEFAULT_PASS:-admin}@rabbitmq:5672/
      - MACHINE_NAME=${MACHINE_NAME:-container}
    networks:
      - default
    ports:
      - ${PORT:-8000}:8000
    volumes:
      - .:/ctsm-api

  tasks:
    image: ghcr.io/ka7eh/ctsm-api:${VERSION:-latest}
    restart: unless-stopped
    entrypoint: /ctsm-api/docker/entrypoint_tasks.sh
    env_file:
      - .env
    environment:
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
      - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER:-admin}:${RABBITMQ_DEFAULT_PASS:-admin}@rabbitmq:5672/
      - MACHINE_NAME=${MACHINE_NAME:-container}
    networks:
      - default
    volumes:
      - .:/ctsm-api

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
    networks:
      - default

networks:
  default:
