version: "3.9"

services:
  api:
    extends:
      file: docker-compose.yaml
      service: api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - DEBUG=1
    volumes:
      - .:/ctsm-api

  rabbitmq:
    extends:
      file: docker-compose.yaml
      service: rabbitmq
    volumes:
      - .:/ctsm-rabbitmq
