"""First migration

Revision ID: a434cc6ab0e7
Revises:
Create Date: 2022-04-18 14:01:21.550652+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a434cc6ab0e7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("compset", sa.String(length=300), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("variables", sa.JSON(), nullable=False),
        sa.Column("fates_indices", sa.String(length=300), nullable=True),
        sa.Column("data_url", sa.String(length=300), nullable=True),
        sa.Column("data_digest", sa.String(length=300), nullable=False),
        sa.Column("driver", sa.String(length=5), nullable=False),
        sa.Column("model_version", sa.String(length=20), nullable=False),
        sa.Column("env", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("date_created", sa.String(length=30), nullable=False),
        sa.Column("create_task_id", sa.String(length=20), nullable=True),
        sa.Column("run_task_id", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_id"), "cases", ["id"], unique=False)
    op.create_table(
        "case_sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("case_id", sa.String(length=32), nullable=False),
        sa.Column("date_created", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_case_sites_id"), "case_sites", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_sites_id"), table_name="case_sites")
    op.drop_table("case_sites")
    op.drop_index(op.f("ix_cases_id"), table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
