"""init

Revision ID: 142fa5e3980d
Revises:
Create Date: 2022-03-08 13:27:21.005808+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "142fa5e3980d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("compset", sa.String(length=300), nullable=False),
        sa.Column("res", sa.String(length=100), nullable=False),
        sa.Column("driver", sa.String(length=5), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_compset"), "cases", ["compset"], unique=False)
    op.create_index(op.f("ix_cases_driver"), "cases", ["driver"], unique=False)
    op.create_index(op.f("ix_cases_id"), "cases", ["id"], unique=False)
    op.create_index(op.f("ix_cases_name"), "cases", ["name"], unique=False)
    op.create_index(op.f("ix_cases_res"), "cases", ["res"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_res"), table_name="cases")
    op.drop_index(op.f("ix_cases_name"), table_name="cases")
    op.drop_index(op.f("ix_cases_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_driver"), table_name="cases")
    op.drop_index(op.f("ix_cases_compset"), table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
