"""First migration

Revision ID: 85158224d3da
Revises:
Create Date: 2022-03-15 13:21:26.638989+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "85158224d3da"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("compset", sa.String(length=300), nullable=False),
        sa.Column("res", sa.String(length=100), nullable=False),
        sa.Column("driver", sa.String(length=5), nullable=False),
        sa.Column("data_url", sa.String(length=300), nullable=False),
        sa.Column("ctsm_tag", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("date_created", sa.String(length=30), nullable=False),
        sa.Column("task_id", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_id"), "cases", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_id"), table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
