"""Add SiteCaseModel

Revision ID: 8b6b0670d3dc
Revises: ef6826c31e5d
Create Date: 2022-03-24 16:05:38.240943+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8b6b0670d3dc"
down_revision = "ef6826c31e5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("case_id", sa.String(length=32), nullable=False),
        sa.Column("date_created", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_case_sites_id"), "case_sites", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_sites_id"), table_name="case_sites")
    op.drop_table("case_sites")
    # ### end Alembic commands ###
