name: Run unit test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, edited ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    # Run the job in this container
    container: python:3.10-bullseye

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install python requirements
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Run Unit Testing
        run: bash ./scripts/run_tests.sh
